jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: azumax/rcatalogue
          tag: test
          extra_build_args: --build-arg COMMIT_SHA=`git rev-parse HEAD` --build-arg RELEASE_TAG=prod 
      - docker/push:
          digest-path: /tmp/digest.txt
          tag: test
          image: azumax/rcatalogue
      - run:
          command: |
            curl -X POST "https://api.newrelic.com/v2/applications/543022464/deployments.json" \
            -H "Api-Key:$NEW_RELIC_API_KEY" -H "Content-Type: application/json" -d '{"deployment": {"revision": "'`git rev-parse HEAD`'","user": "CircleCI","timestamp": "'`date +'%Y-%m-%dT%H:%M:%S'Z`'"}}'
  update-kubernetes:
    executor: docker/docker
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: Socks
          aws-region: ap-northeast-1
          install-kubectl: true
      - run:
          command: |
            kubectl -n sock-shop-nr rollout restart deploy catalogue
          name: Test cluster
orbs:
  docker: circleci/docker@1.7.0
  kubernetes: circleci/kubernetes@0.12.0
  aws-cli: circleci/aws-cli@2.0.1
  aws-eks: circleci/aws-eks@1.1.0
version: 2.1
workflows:
  workflow:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: 
                - master 
      - update-kubernetes:
          requires:
            - build-and-push
          filters:
            branches:
              only: 
                - master 
                
