jobs:
  build-and-push:
    executor: docker/docker
    steps:
      # - setup_remote_docker
      # - checkout
      # - docker/check
      # - docker/build:
      #     image: azumax/rcatalogue
      #     extra_build_args: --build-arg COMMIT_SHA=`git rev-parse HEAD` --build-arg RELEASE_TAG=prod 
      # - docker/push:
      #     digest-path: /tmp/digest.txt
      #     image: azumax/rcatalogue
      # - run:
      #     command: |
      #       echo "Digest is: $(</tmp/digest.txt)"
      - aws-cli/setup:
          profile-name: default
      - run:
          command: |
            aws eks list-clusters
          name: check aws
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: Socks
          aws-region: ap-northeast-1
          aws-profile: default
          install-kubectl: true
      - run:
          command: |
            cat /home/circleci/.kube/config
          name: check config
      - run:
          command: |
            kubectl get services -A
          name: Test cluster
orbs:
  docker: circleci/docker@1.7.0
  kubernetes: circleci/kubernetes@0.12.0
  aws-cli: circleci/aws-cli@2.0.1
  aws-eks: circleci/aws-eks@1.1.0
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push
