name: CI_INTEGRATION

on:
  status:

  workflow_dispatch:
concurrency:
  ci_integration

jobs:
  syncStatus:
    environment: CIRCLECI_INTEGRATION
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - shell: bash
        env:
          CIRCLECI_KEY: ${{ secrets.CIRCLECI_KEY }}
          NR_ACCOUNT: ${{ secrets.NR_ACCOUNT }}
          NR_KEY: ${{ secrets.NR_KEY }}
          NR_II_KEY: ${{ secrets.NR_II_KEY }}
        run: |
          node scripts/status.js; sleep 10;
